### ISSUE TITLE
listtransactions and listunspent not showing transactions since last start

### ISSUE THREAD

**Issue by broyhill** [ioncoincore/ion#1]
### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1. start wallet
2. listtransactions, listunspent
3. send/receive tx
4. listtransactions, listunspent

**Comment by cevap** [comment]
Issue resolved and closed:  https://github.com/cevap/ion/commit/5491b06ab33046dec298b68307a1e834a93f3b0b
