### ISSUE TITLE
appoint roles and tasks of ion core

### ISSUE THREAD

**Issue by cryptolinux** [ioncoincore/ion#10]
Korvas128 is appointed to manage this project, before any further nomination (https://github.com/ioncoincore/ion/issues/3 and https://github.com/ioncoincore/ion/issues/9) can be done, roles and tasks should be defined. Please follow the project about the status and each role/nominations should take place in separate project card/task/issue.

**Comment by Cryptoformer** [comment]
I can see there are three roles to manage this project.

- Project in general
- Development
- Financial

That's basically it, any thoughts on that?

**Comment by cryptolinux** [comment]
@Cryptoformer, here are few thoughs, in short collaboration is the key word, in longer explanation:

- that would be a good start, this project consists of several parts and one person obviously can not know everything, by that managers is already good start as they could manage to organize the rest. Open Source development is possible for every user and one does not require to wait for nominations to create pull request. @korvasc is now this main project manager and his tasks need to be defined together with him
- A lot is already defined and set, those who manage should make sure that nothing is undocumented as well as to hold on quite a lot set in https://github.com/ioncoincore/ion/tree/master/doc documentation. During the reading, one can test it and update documents, in future no pull requests should happen without proper holding on release process and other measures.
- Let's put a structure together for managing and what managers would need to do, all of that, please after reading available docs.
- When we speak about write access, then we only speak about managers of ioncoincore, separate repos, separate contributors, separate rights, but all clearly defined as well as goals of why they exist. Other contributors do not need write access. By that we should define which roles have which rights, as well as for what.
- About development: this community will require developers and this will be probably available at later point where project has a clear structure and processes as well as goals and priorities.
- About financial department as well as discussion about it, it is pointless until there are some financial funds and questions about it is probably something that will be addressed during transition phase and before ionomy makes any statement about it, it would be pointless to talk about it as we do not need to waste time on speculation.
  - masternode owners can independently create funds proposing whatever one thinks, such things can and should not be managed by ion core team
- But as you suggest, I would define instead of Financial department first a controlling, where I would immediately suggest:
  - [x] LordDarkHelmet if one would ask me who could overtake this task.
- It would be be more productive if one already read documentation and if one is not new to github and concepts of current project.

**Comment by LordDarkHelmet** [comment]
If you need my assistance, I am willing to help. Please be aware that my time is limited and I may not be available for tasks that require immediate attention. 

I am happy to see that you are defining rolls and responsibilities. This will pay dividends down the road. Like every project we should ensure that there is no single point of failure, and that no person can cause catastrophe if the decide to become malicious.

**Comment by korvasc** [comment]
LordDarkHelmet

Hope you can help

We need someone to understand the communities financial position so moving forwards the community can better plan .ie, hosting costs, bounties, etc. So someone to drill into the numbers that we get from Adam    

For reference, below is what I posted on a  different card (Git hub is a learning curve for me so a cut n paste is just me being quick whilst I get to grips with github)

----------------------------------------------------------------------------------------------------------------------------------------

Project Manager Myself

My job is to give structure and to also help facilitate a smooth transition. I'm a jack for all trades master of none. I am here to assist both Development & Finance

Development ckti

Even though ckti is paid for by Ionomy he is also well respected by the community, I see no conflict of Interests.

Finance Propose LordDarkHelmet

Again a well-respected long time member of this community with the expertise to be in a position to advise on the communities financial position.

**Comment by LordDarkHelmet** [comment]
The role for Finance is a bit nebulous, but I am happy to help. 

We should map out responsibilities and expectations. Basically who is responsible for what, and how those people are held accountable. To me it is unclear what we need for my proposed roll. Is it reporting on how funds and coins are spent? Is is making decisions on who gets funds and who does not? Or is it as simple as breaking down the costs to run a masternode to the community?

By clearly defining each roll, and assigning specific objectives, we can be accountable to the community and provide the information and leadership that is needed.

**Comment by korvasc** [comment]
Your help is an important step forward for IONcore so again thankyou. As we go through the process of transition roles will go from generic place holders to be clearly defined with names & responsibilities 

LordDarkHelmet - IONcore Financial Controller - IONcore's money man

Responsibilities : 

And understanding of ION core's financial position so before any costs are incurred we understand its financial impact 
IONcore Developer Fund responsibility

Moving forwards an understanding of our financial position is a critical FIRST step. Your role will be a benchmark for other roles. Zero ambiguity and clear lines of responsibilities. My job as facilitator is to help make sure this happens so as we work through the different financial issues it will help build a list fo responsibilities for the other roles. 

Hope this makes sense

**Comment by korvasc** [comment]
Now resource confirmed in Project management, Development & Finance I am now happy to close
