### ISSUE TITLE
transfer ioncoin.org domain ownership

### ISSUE THREAD

**Issue by cryptolinux** [ioncoincore/ion#11]
reopenning it, we need some confirmation about it as well as to show the ownership

Im not sure who we is... but its completed and in @korvasc  sole control

**Comment by korvasc** [comment]
> reopenning it, we need some confirmation about it as well as to show the ownership
> 
> Im not sure who we is... but its completed and in @korvasc sole control

I can confirm I have the domain will update Github tomorrow with details

**Comment by cryptolinux** [comment]
@korvasc thanks for the update

**Comment by korvasc** [comment]
![Ioncoredomainconf](https://user-images.githubusercontent.com/25220382/97104658-87e4bc80-16ad-11eb-8d62-1e98aab72479.jpg)

Confirmation transfer note expiration Jul 3, 2021
