### ISSUE TITLE
[gitian][maintenance][question] Gitian building FAQ/Help

### ISSUE THREAD

**Issue by cevap** [ioncoincore/ion#24]
#### FAQ/Additional notes
From my experience, out of 10 people, 9 did not configure their gitian properly, here are remarks which I think would improve this statistics a lot:

- **Wrong username**
  Some users press enter, enter, ... during ubuntu installation where they end up with a user ubuntu where they do not change in their scripts from the guide to according user (_[in most guides it is gitianuser](https://github.com/ioncoincore/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-debian-for-gitian-building)_)
- **Bad setup of base image**
  For some reason (_probably because there is no documentation except inline one of gitian-build.py script_), most who managed to set **wrong username**, they also [created their base images](https://github.com/ioncoincore/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-the-gitian-image), instead to use gitian-build.py. Doing it manually is not wrong, but will likely give you more chance to make mistake.
- **No/Empty /etc/rc.local**
  This happens mostly when users save [this script into a file and run it](https://github.com/ioncoincore/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-debian-for-gitian-building), where after running `sudo -s` script does not continue as root. This is something that happens mostly to windows users who are unexperienced with linux systems.
- Confusion by **--no-commit** and **--commit** switches
  If somebody looks into gitian-build.py, then there is very clear description of what both of them mean:
  - `--no-commit`: [Do not commit anything to git](https://github.com/ioncoincore/ion/blob/2e2617ed8034c298bbd75025ac1b2611ca329d2f/contrib/gitian-build.py#L174) (_here it is about gitian.sigs, signatures and with this switch no commit will be created_)
  - `--commit`: [Indicate that the version argument is for a commit or branch](https://github.com/ioncoincore/ion/blob/2e2617ed8034c298bbd75025ac1b2611ca329d2f/contrib/gitian-build.py#L160) (_It means that if you use a branch name or some commit hash, then you have to use `--commit` switch, example: `gitian-build.py --build --commit YourLongGPGID master`_)

##### I had one of those errors, repaired according the docu and it still does not work, what should I do?

1. Remove base image `rm ~/gitian-builder/*-bionic-*`
1. Reboot your VM `sudo shutdown -r now` (_you could also use `sudo reboot`, `reboot`_)
1. Check `/etc/rc.local` script
  _If it is empty or does not exist, please follow [according part of the gitian guide](https://github.com/ioncoincore/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-debian-for-gitian-building)._
1. Check your `~/.profile` for wrong username
  _[Recheck which username you used to run setup](https://github.com/ioncoincore/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md#setting-up-debian-for-gitian-building)_
1. Check if interface `br0` exists
  Run `ifconfig -a | grep br0` and if there is no `br0`, please run rc.local script: `sudo /etc/rc.local`.
  ***Note:*** _There could be lxcbr0: `lxcbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500`, in setup step we use br0, ensure that interface you do define in setup is available_
1. Reboot your VM `sudo shutdown -r now` (_you could also use `sudo reboot`, `reboot`_)
1. Setup gitian, build base image with gitian-build.py script
  `gitian-build.py --setup $SIGNER $VERSION`
  If you want to setup docker: `gitian-build.py --docker --setup $SIGNER $VERSION`

##### My gitian-build.py starts building but gets terminated with the timeout error

Your GPG key for github (_this is $SIGNER variable_) ***has set a password***.  Create GPG without password for building without user interruption. By default, ubuntu and debian are set not to allow a user to create GPG without password, you can many tools, one of them would be kleopatra 
- Linux (_Ubuntu/Debian_)  `sudo apt-get install kleopatra` , 
- Windows: [Gpg4Win](https://www.gpg4win.org/) (_it includes kleopatra_)

**Comment by MitchellCash** [comment]
👍 Probably good to put this sort of information into the wiki

**Comment by cevap** [comment]
yes, maybe we should add additional troubles which we know other did run into, what I described in first post covers a lot but we need to add additionaly:

- GPG part
- SSH part

as well to add to our guides gpg fetching before starting to buld, maybe the best would be if thats a part of gitian-build.py.

**Comment by raid12345678** [comment]
This is very helpful. I used these same steps to solve my build issues recently
