### ISSUE TITLE
[macOS] ION core does not start "Can’t be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by RdeWilde** [ioncoincore/ion#7]
### Describe the issue
After downloading and installing the ION core v5.0.0 .dmg-file on macOS Catalina, the application won't start. Instead it gives this error: 

> Can’t be opened because Apple cannot check it for malicious software

#### If so, please list the steps to reproduce below:
1. Download the ION core v5.0.0 .dmg-file on macOS Catalina (or later)
2. Install it onto your computer by dragging it into the folder in the installation window
3. Try to start the application ION core, for example using Launchpad

### Expected behaviour
The application should open up.

### Actual behaviour
It shows this error and won't start:
> Can’t be opened because Apple cannot check it for malicious software

### What version of Ion Core are you using?
https://github.com/ioncoincore/ion/releases/tag/v5.0.00
https://github.com/ioncoincore/ion/releases/download/v5.0.00/ioncore-5.0.00.osx-signed.dmg

### Machine specs:
- OS: macOS Catalina

### Any extra information that might be useful in the debugging process.

> This is due to an update in the way that gatekeeper works on Catalina. It’s looking for “notorisation” of the app. It’s effectively a certificate of good standing that is obtained by the dev uploading their app to Apple to check for malicious code which is then stapled to the app. It’s one step further than having a app signed with a developer cert.
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

I "solved" this for now by disabling the check, running this from the terminal:
`sudo xattr -rd com.apple.quarantine /Applications/Ion-Qt.app`

**Comment by RdeWilde** [comment]
AtomSmasher suggested an even easier workaround, you can just open system settings > security and allow the app to open anyways.

**Comment by korvasc** [comment]
This has nothing to do with the task of transition so I'm closing it.

**Comment by korvasc** [comment]
This has nothing to do with the task of transition so I'm closing it
