### ISSUE TITLE
[bug][snap] wallet corrupted after snap upgrade

### ISSUE THREAD

**Issue by cevap** [ioncoincore/ion#75]
**Describe the bug**
After snap updates wallet.dat might become corrupt due to openssl change

**Expected behavior**
Wallet should not be corrupted

**Additional context**
Proposal solution is to build with depends folder: #74

**Comment by raid12345678** [comment]
@cevap  is this issue clossfied as a duplicate or do we need to have this issue in open status until the issue is fixed?

**Comment by cevap** [comment]
it is closed now, snap builds from depends folder using same dependencies as our deterministic releases. I will close this issue as it is resolved.
